name: app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  camera: ^0.10.0+1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/IMG_7421.png
    - assets/icon.png

 
